// Copyright 2020 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	mindsporev1 "gitee.com/mindspore/ms-operator/pkg/apis/mindspore/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMSJobs implements MSJobInterface
type FakeMSJobs struct {
	Fake *FakeKubeflowV1
	ns   string
}

var msjobsResource = schema.GroupVersionResource{Group: "kubeflow.org", Version: "v1", Resource: "msjobs"}

var msjobsKind = schema.GroupVersionKind{Group: "kubeflow.org", Version: "v1", Kind: "MSJob"}

// Get takes name of the mSJob, and returns the corresponding mSJob object, and an error if there is any.
func (c *FakeMSJobs) Get(name string, options v1.GetOptions) (result *mindsporev1.MSJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(msjobsResource, c.ns, name), &mindsporev1.MSJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*mindsporev1.MSJob), err
}

// List takes label and field selectors, and returns the list of MSJobs that match those selectors.
func (c *FakeMSJobs) List(opts v1.ListOptions) (result *mindsporev1.MSJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(msjobsResource, msjobsKind, c.ns, opts), &mindsporev1.MSJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &mindsporev1.MSJobList{ListMeta: obj.(*mindsporev1.MSJobList).ListMeta}
	for _, item := range obj.(*mindsporev1.MSJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mSJobs.
func (c *FakeMSJobs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(msjobsResource, c.ns, opts))

}

// Create takes the representation of a mSJob and creates it.  Returns the server's representation of the mSJob, and an error, if there is any.
func (c *FakeMSJobs) Create(mSJob *mindsporev1.MSJob) (result *mindsporev1.MSJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(msjobsResource, c.ns, mSJob), &mindsporev1.MSJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*mindsporev1.MSJob), err
}

// Update takes the representation of a mSJob and updates it. Returns the server's representation of the mSJob, and an error, if there is any.
func (c *FakeMSJobs) Update(mSJob *mindsporev1.MSJob) (result *mindsporev1.MSJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(msjobsResource, c.ns, mSJob), &mindsporev1.MSJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*mindsporev1.MSJob), err
}

// Delete takes name of the mSJob and deletes it. Returns an error if one occurs.
func (c *FakeMSJobs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(msjobsResource, c.ns, name), &mindsporev1.MSJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMSJobs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(msjobsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &mindsporev1.MSJobList{})
	return err
}

// Patch applies the patch and returns the patched mSJob.
func (c *FakeMSJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *mindsporev1.MSJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(msjobsResource, c.ns, name, data, subresources...), &mindsporev1.MSJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*mindsporev1.MSJob), err
}
