# permissions for end users to edit msjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: msjob-editor-role
rules:
- apiGroups:
  - mindspore.gitee.com
  resources:
  - msjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mindspore.gitee.com
  resources:
  - msjobs/status
  verbs:
  - get
