// Copyright 2020 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "gitee.com/mindspore/ms-operator/pkg/apis/mindspore/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// MSJobLister helps list MSJobs.
type MSJobLister interface {
	// List lists all MSJobs in the indexer.
	List(selector labels.Selector) (ret []*v1.MSJob, err error)
	// MSJobs returns an object that can list and get MSJobs.
	MSJobs(namespace string) MSJobNamespaceLister
	MSJobListerExpansion
}

// mSJobLister implements the MSJobLister interface.
type mSJobLister struct {
	indexer cache.Indexer
}

// NewMSJobLister returns a new MSJobLister.
func NewMSJobLister(indexer cache.Indexer) MSJobLister {
	return &mSJobLister{indexer: indexer}
}

// List lists all MSJobs in the indexer.
func (s *mSJobLister) List(selector labels.Selector) (ret []*v1.MSJob, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.MSJob))
	})
	return ret, err
}

// MSJobs returns an object that can list and get MSJobs.
func (s *mSJobLister) MSJobs(namespace string) MSJobNamespaceLister {
	return mSJobNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// MSJobNamespaceLister helps list and get MSJobs.
type MSJobNamespaceLister interface {
	// List lists all MSJobs in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.MSJob, err error)
	// Get retrieves the MSJob from the indexer for a given namespace and name.
	Get(name string) (*v1.MSJob, error)
	MSJobNamespaceListerExpansion
}

// mSJobNamespaceLister implements the MSJobNamespaceLister
// interface.
type mSJobNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all MSJobs in the indexer for a given namespace.
func (s mSJobNamespaceLister) List(selector labels.Selector) (ret []*v1.MSJob, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.MSJob))
	})
	return ret, err
}

// Get retrieves the MSJob from the indexer for a given namespace and name.
func (s mSJobNamespaceLister) Get(name string) (*v1.MSJob, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("msjob"), name)
	}
	return obj.(*v1.MSJob), nil
}
